// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp8TnSCXhg8mvPZ7y8WNBRuKfT-VIBpKA',
    appId: '1:360584738490:web:c1d9baecbb2130a19d3483',
    messagingSenderId: '360584738490',
    projectId: 'instagram-clone-91936',
    authDomain: 'instagram-clone-91936.firebaseapp.com',
    storageBucket: 'instagram-clone-91936.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApTNAufo0upxlMVSfIkXFjaL2NoB2HVRI',
    appId: '1:360584738490:android:c383994a885063799d3483',
    messagingSenderId: '360584738490',
    projectId: 'instagram-clone-91936',
    storageBucket: 'instagram-clone-91936.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZSdzm5F2bIUsdR2NdXe_25qT857Skw_A',
    appId: '1:360584738490:ios:68813033ee2cef559d3483',
    messagingSenderId: '360584738490',
    projectId: 'instagram-clone-91936',
    storageBucket: 'instagram-clone-91936.appspot.com',
    iosBundleId: 'com.example.flutterInstagram',
  );
}

